stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public  # Создаём директорию public, если её нет
    - cp -r * public/  # Копируем все файлы в public
  artifacts:
    paths:
      - public  # Указываем, что для деплоя нужно использовать директорию public
  only:
    - Main  # или другая ветка для деплоя